name = "hardly-know-her-telegram-bot"
main = "src/main.js"
compatibility_date = "2024-01-01"
send_metrics = true
kv_namespaces = [
  { binding = "KV_STORE", id = "5f1b958a44be4df5b768ddb5e420da1e" },
]

rules = [{ type = "ESModule", globs = ["**/*.js"], fallthrough = true }]

[triggers]
crons = ["*/5 * * * *", "0 8 * * *"]
